<script lang="ts">
	import type { Article, i18nType } from '$lib/types';

	import { createEventDispatcher, getContext, onMount } from 'svelte';
	import { toast } from 'svelte-sonner';
	import { slide } from 'svelte/transition';

	import { addNewArticle } from '$lib/apis/articles';
	import { getSeriesByName } from '$lib/apis/series';
	import { updateUserSavedArticles } from '$lib/apis/users';
	import type { Model } from '$lib/stores';
	import {
		ExpGradeSelected,
		activeArticle,
		activeSupportSection,
		activeSupportStep,
		config,
		hideSupportWidgetBtn,
		isSupportStepDetailsOpen,
		models,
		mostRecentStep,
		mountedArticleSteps,
		settings,
		showSidebar
	} from '$lib/stores';
	import { generateReadingText, isErrorWithDetail, isErrorWithMessage, titleizeWords } from '$lib/utils';
	import type { MarkedOptions } from 'marked';
	import { marked } from 'marked';
	import readingTime from 'reading-time/lib/reading-time';

	import Controls from '$lib/components/chat/Controls/Controls.svelte';
	import Modal from '$lib/components/common/Modal.svelte';
	import Tooltip from '$lib/components/common/Tooltip.svelte';
	import Navbar from '$lib/components/layout/Navbar.svelte';

	import ArticleStep from './ArticleStep.svelte';
	import DetailsGetSupport from './DetailsGetSupport.svelte';
	import { SaveIcon } from 'lucide-svelte';

	const i18n: i18nType = getContext('i18n');
	const dispatch = createEventDispatcher();

	let lang = $i18n.language;

	let articleWrapper: HTMLDivElement;
	let observer: IntersectionObserver;
	let articleId: string;
	let hasRelatedVideo = false;
	let expandedSteps = new Set<number>();
	let stepElements: HTMLDivElement[] = [];
	let objectiveElement: HTMLDivElement;
	let relatedVideo: object | null = null;
	let expanded = false;
	let isSticky = false;
	let showModelSelector = true;
	let showControls = false;
	let selectedModels = [''];
	let atSelectedModel: Model | undefined;
	let selectedModelIds = [];
	let largeScreen = false;
	let timeToRead: number | null = null;

	$: selectedModelIds = atSelectedModel !== undefined ? [atSelectedModel.id] : selectedModels;
	$: console.log('selectedModels', selectedModels);
	$: getSupportDivs = [] as HTMLDivElement[];
	$: activeStep = -1;

	const renderer = new marked.Renderer();

	// For code blocks with simple backticks
	renderer.codespan = (code) => {
		return `<code>${code.replaceAll('&amp;', '&')}</code>`;
	};

	// Open all links in a new tab/window (from https://github.com/markedjs/marked/issues/655#issuecomment-383226346)
	const origLinkRenderer = renderer.link;

	renderer.link = (href, title, text) => {
		const html = origLinkRenderer.call(renderer, href, title, text);
		return html.replace(/^<a /, '<a target="_blank" rel="nofollow" ');
	};

	const { extensions, ...defaults } = marked.getDefaults() as MarkedOptions & {
		// eslint-disable-next-line @typescript-eslint/no-explicit-any
		extensions: any;
	};

	const getClosestSupportDiv = () => {
		let divs = Array.from(getSupportDivs) as Array<HTMLDivElement>;
		divs.unshift(objectiveElement);
		divs = divs;
		let { closestSection, currentStep } = divs.reduce<{
			closestDistance: number;
			closestSection: string | null;
			currentStep: string | null;
		}>(
			(acc, div) => {
				const rect = div.getBoundingClientRect();
				const divCenter = rect.top + rect.height / 2;
				const screenCenter = window.innerHeight / 2;
				const distance = Math.abs(screenCenter - divCenter);
				return distance < acc.closestDistance
					? {
							closestDistance: distance,
							closestSection: div.getAttribute('data-section'),
							currentStep: div.getAttribute('data-step')
					  }
					: acc;
			},
			{ closestDistance: Infinity, closestSection: null, currentStep: null }
		);
		if (closestSection) {
			activeSupportSection.set(closestSection);
		}
		if (currentStep) {
			mostRecentStep.set(parseInt(currentStep));
		}
	};
	// Function to add generated articles, fails for already added articles
	const addArticle = async (article: Article) => {
		const series = await getSeriesByName(localStorage.token, article.series ?? '').catch((error) => {
			// This is expected to fail for articles that were not generated by a user
			console.error(error);
			return null;
		});
		if (series) {
			const newArticle = await addNewArticle(localStorage.token, {
				id: article.id,
				title: article.title,
				document_id: article.document_id,
				objective: article.objective,
				category: article.category,
				url: article.url,
				applicable_devices: article.applicable_devices ?? [],
				introduction: article.introduction,
				steps: article.steps ?? [],
				revision_history: article.revision_history ?? [],
				series_id: series.id
			}).catch((error) => {
				console.error(error);
				if (isErrorWithDetail(error)) {
					toast.error(error.detail);
				} else if (isErrorWithMessage(error)) {
					toast.error(error.message);
				} else {
					toast.error('An error occurred');
				}
				return null;
			});

			if (newArticle) {
				toast.success($i18n.t('Article added successfully to database'));
				activeArticle.set(newArticle);
			}
		}
	};

	const extractText = (element: HTMLElement): string => {
		return element.innerText;
	};
	let testTime: string | null = '1 minute read';
	onMount(async () => {
		window.addEventListener('scroll', getClosestSupportDiv);

		const mediaQuery = window.matchMedia('(min-width: 1024px)');
		const handleMediaQuery = (e: MediaQueryListEvent) => {
			largeScreen = e.matches;
		};

		mediaQuery.addEventListener('change', handleMediaQuery);
		handleMediaQuery({ matches: mediaQuery.matches } as MediaQueryListEvent);

		if ($settings.models) {
			selectedModels = $settings.models;
		} else if ($config?.default_models) {
			selectedModels = $config.default_models.split(',');
		} else {
			selectedModels = [''];
		}

		if (articleWrapper) {
			testTime = readingTime(extractText(articleWrapper)).text;
			console.log('testTime', testTime);
		}
		selectedModels = selectedModels.map((modelId) => ($models.map((m) => m.id).includes(modelId) ? modelId : ''));
		// (async () => {
		// 	if ($page.url.searchParams.has('id')) {
		// 		activeArticle.set(await getArticleById(localStorage.token, $page.url.searchParams.get('id')!));
		// 	} else if ($page.url.searchParams.has('document_id')) {
		// 		activeArticle.set(await getArticleByDocumentId(localStorage.token, $page.url.searchParams.get('document_id')!));
		// 	} else if ($page.params.id) {
		// 		activeArticle.set(await getArticleById(localStorage.token, $page.params.id));
		// 	}
		// })();
		return new Promise((resolve, reject) => {
			window.removeEventListener('scroll', getClosestSupportDiv);
			mediaQuery.removeEventListener('change', handleMediaQuery);
			resolve(void 0);
		});
		// return () => {
		// 	window.removeEventListener('scroll', getClosestSupportDiv);
		// 	mediaQuery.removeEventListener('change', handleMediaQuery);
		// };
	});

	$: {
		console.log('mostRecentStep', $mostRecentStep);
	}

	$: {
		let step = $mountedArticleSteps.at($mostRecentStep);
		if (step) {
			activeSupportStep.set(step.step_number);
		}
	}

	const stepSupportDetailsOpen = (e: CustomEvent<{ index: number }>) => {
		const { index } = e.detail;
		activeStep = index;
		if (!expandedSteps.has(index)) {
			expandedSteps.add(index);
		} else {
			expandedSteps.delete(index);
			activeStep = -1;
		}
	};

	const stepSupportDetailsClose = (e: CustomEvent<{ index: number }>) => {
		const { index } = e.detail;
		expandedSteps.delete(index);
		activeStep = -1;
	};

	function handleOpen(event: CustomEvent<{ index: number }>) {
		isSupportStepDetailsOpen.set(true);
		console.log('handleOpen', event);
		console.log('mostRecentStep', $mostRecentStep);
		expandedSteps.add(event.detail.index);
		console.log('expandedSteps', expandedSteps);
	}
	function handleClose(event: CustomEvent<{ index: number }>) {
		console.log('handleClose', event);
		expandedSteps.delete(event.detail.index);
		console.log('expandedSteps', expandedSteps);
		// $isSupportStepDetailsOpen = false;
		mostRecentStep.set(-1);
	}

	$: isStepActive = expandedSteps.has(activeStep);

	$: title = $activeArticle?.title ?? 'Article';

	$: chatControlModels = selectedModelIds.reduce((a, e, i, arr) => {
		const model = $models.find((m) => m.id === e);
		if (model) {
			return [...a, model];
		}
		return a;
	}, [] as Model[]);

	$: time = $activeArticle
		? articleWrapper
			? readingTime(extractText(articleWrapper)).text
			: readingTime(generateReadingText($activeArticle)).text
		: '12 minute read';

	const concatSupportString = (title: string, stepNum: number) => {
		return `${title} | Step ${stepNum}`;
	};

	const _updateUserSavedArticles = async (articleId: string) => {
		const articleIds = await updateUserSavedArticles(localStorage.token, articleId).catch((err) => {
			toast.error($i18n.t('Failed to save article {{title}} to your account', { title: $activeArticle?.title }));
			return null;
		});
		if (articleIds) {
			dispatch('save');
		}
	};
</script>

<div
	class="h-screen max-h-[100dvh] {$showSidebar ? 'md:max-w-[calc(100%-260px)]' : ''} w-full max-w-full flex flex-col"
>
	{#if $settings?.backgroundImageUrl ?? null}
		<div
			class="absolute {$showSidebar
				? 'md:max-w-[calc(100%-260px)] md:translate-x-[260px]'
				: ''} top-0 left-0 w-full h-full bg-cover bg-center bg-no-repeat"
			style="background-image: url({$settings.backgroundImageUrl})  "
		/>

		<div
			class="absolute top-0 left-0 w-full h-full bg-gradient-to-t from-white to-white/85 dark:from-gray-900 dark:to-[#171717]/90 z-0"
		/>
	{/if}

	<Navbar
		{title}
		bind:selectedModels
		bind:showModelSelector
		bind:showControls
		shareEnabled={false}
		chat={{}}
		initNewChat={() => {}}
	/>
	{#if $activeArticle}
		<div
			bind:this={articleWrapper}
			id="eot-doc-wrapper"
			class="w-full bg-gray-50 dark:bg-gray-900 text-gray-850 dark:text-gray-50 pb-8 p-4"
		>
			<div class="flex flex-col mx-auto {$showSidebar ? 'w-[calc(100%-16px)]' : 'w-[calc(100%-50px)]'}">
				<div class="rounded-xl">
					<div>
						<h1 class="text-3xl text-left font-bold text-gray-850 dark:text-gray-50 my-6 text-pretty">
							{$activeArticle.title}
						</h1>
						<div
							class="control-bar py-4 px-8 bg-gray-100 text-gray-850 dark:bg-gray-850 dark:text-gray-50 rounded-md shadow-md"
						>
							<div class="flex items-center justify-between">
								<div class="flex flex-col justify-start">
									<p class="text-md font-bold">{$i18n.t('Document Id')}:</p>
									<p class="text-sm">{$activeArticle.document_id}</p>
								</div>
								<div class="flex items-center">
									<button
										class="flex items-center justify-center self-end py-2 px-4 rounded-md bg-gray-300 hover:bg-gray-200 dark:bg-gray-700 dark:hover:bg-gray-600"
										on:click={async () => {
											await _updateUserSavedArticles($activeArticle.id);
										}}
									>
										<Tooltip content={$i18n.t('Save to your account')}>
											<SaveIcon class="w-5 h-5 text-gray-500" />
										</Tooltip>
									</button>
								</div>
							</div>
						</div>
						<h2 class="text-2xl my-6 font-bold text-blue-950 dark:text-blue-100">Objective</h2>
						<div data-section="Objective" bind:this={objectiveElement}>
							<p>{$activeArticle.objective}</p>
						</div>

						{#if $activeArticle.applicable_devices && $activeArticle.applicable_devices.length > 0}
							<h2 class="text-2xl my-6 font-bold text-blue-950 dark:text-blue-100">
								Applicable Devices | Software Version
							</h2>
							<ul class="text-gray-850 dark:text-gray-50">
								{#each $activeArticle.applicable_devices as device}
									{#if device.device && device.software && device.datasheet_link && device.software_link}
										<li>
											{device.device}
											<a class="text-blue-950 hover:text-blue-900" target="_blank" href={device.datasheet_link}>
												(Datasheet)
											</a>
											| {device.software}
											<a class="text-blue-950 hover:text-blue-900" target="_blank" href={device.software_link}>
												(Download Latest)
											</a>
										</li>
									{:else if device.device && device.software && device.datasheet_link}
										<li>
											{device.device}
											<a class="text-blue-950 hover:text-blue-900" target="_blank" href={device.datasheet_link}>
												(Datasheet)
											</a>
											| {device.software}
										</li>
									{:else if device.device && device.software && device.software_link}
										<li>
											{device.device} | {device.software}
											<a class="text-blue-950 hover:text-blue-900" target="_blank" href={device.software_link}>
												(Download Latest)
											</a>
										</li>
									{:else if device.device && device.software}
										<li>
											{device.device}{#if device.software}
												| {device.software}{/if}
										</li>
									{:else}
										<li>{device.device}</li>
									{/if}
								{/each}
							</ul>
						{/if}
						{#if $activeArticle.introduction}
							<h2 class="text-2xl my-6 font-bold text-blue-950 dark:text-blue-50">Introduction</h2>
							{@html marked.parse($activeArticle.introduction, {
								...defaults,
								gfm: true,
								breaks: true,
								renderer
							})}
						{/if}
					</div>
				</div>
				<div
					class="cdt-best-practice text-base bg-[#0d274d] p-2.5 text-white m-8 rounded-[5px] shadow-[0_0_16px_0_rgba(43, 85, 146, 0.2) border-l-[5px] border-green-600"
				>
					<p>
						Backup your configuration prior to upgrading the firmware. You can do this by navigating to <b
							>Administration &gt; File Management &gt; File Operations</b
						> in the menu. Download a copy of the running configuration to your PC. It is not recommended to do a firmware
						upgrade of your device remotely.
					</p>
				</div>
				<div class="flex items-center justify-between max-h-full flex-wrap my-2.5">
					<div class="nested-1 flex items-center justify-center space-x-2.5">
						<svg
							xmlns="http://www.w3.org/2000/svg"
							viewBox="0 0 80 80"
							style="width: 50px;display:inline-block;"
							width="40"
							stroke="currentColor"
							stroke-width="1.5"
							><path
								d="M58,39.25H46.70581a6.74732,6.74732,0,0,0-13.41162,0H22a12.75,12.75,0,0,0,0,25.5H57.29419a6.75,6.75,0,1,0,0-1.5H22a11.25,11.25,0,0,1,0-22.5H33.29419a6.74732,6.74732,0,0,0,13.41162,0H58a12.75,12.75,0,0,0,0-25.5H22.70581a6.687,6.687,0,0,0-.66064-2.23462L25.06055,10,24,8.93945l-2.78308,2.78308A6.74807,6.74807,0,1,0,22.70581,16.75H58a11.25,11.25,0,0,1,0,22.5Zm6,19.5A5.25,5.25,0,1,1,58.75,64,5.25605,5.25605,0,0,1,64,58.75ZM40,45.25A5.25,5.25,0,1,1,45.25,40,5.25605,5.25605,0,0,1,40,45.25Zm-24-24a5.25009,5.25009,0,1,1,4.13525-8.44586L16,16.93945l-2-2L12.93945,16l2.53028,2.53027a.74971.74971,0,0,0,1.06054,0l4.36939-4.36944A5.19508,5.19508,0,0,1,21.25,16,5.25605,5.25605,0,0,1,16,21.25Z"
								class="s-qHuZzP0FnHPs"
							/></svg
						>
						<p class="text-sm md:block">{$i18n.t('Estimated')}:</p>
						<span class="text-sm">{time}</span>
					</div>
				</div>
				{#each $activeArticle.steps as step, index}
					<div class="my-8" bind:this={stepElements[index]}>
						{#if step.step_number === 1}
							<h4 class="text-xl font-bold my-5 text-blue-950 dark:text-blue-100">{step.section}</h4>
						{/if}
						<ArticleStep {index} {step} bind:active={isStepActive} />

						<div
							class="getSupportStep border border-gray-400 transition-all duration-250 ease-in bg-gray-50 text-gray-850 dark:bg-gray-850 dark:text-gray-50 w-full max-w-[1000px] rounded-md hover:bg-gray-100"
							data-section={step.section}
							data-step={index}
							bind:this={getSupportDivs[index]}
							class:hidden={$ExpGradeSelected === 'Lightly Guided'}
						>
							<DetailsGetSupport
								{selectedModels}
								open={expandedSteps.has(index)}
								{index}
								currentStepStr={concatSupportString(titleizeWords(step.section), step.step_number)}
								{step}
								on:openStepSupport={stepSupportDetailsOpen}
								on:closeStepSupport={stepSupportDetailsClose}
							/>
						</div>
					</div>
				{/each}
				<slot />
			</div>
			{#if $activeArticle.revision_history && $activeArticle.revision_history.length > 0}
				<div class="m-4">
					<table class="table-auto border-collapse border-spacing-2 border-2 border-gray-600">
						<caption class="caption-top mb-2 font-bold text-lg">{$i18n.t('Revision History')}</caption>
						<thead>
							<tr>
								{#each [$i18n.t('Revision'), $i18n.t('Publish Date'), $i18n.t('Comments')] as header}
									<th class="bg-blue-950 text-gray-50 font-['CiscoSansLight'] font-bold p-2 border-2 border-slate-700"
										>{header}</th
									>
								{/each}
							</tr>
						</thead>
						<tbody>
							{#each $activeArticle.revision_history ?? [] as history, i (i)}
								<tr>
									<td class="border-2 border-gray-600 p-2">{history.revision}</td>
									<td class="border-2 border-gray-600 p-2">{new Date(history.publish_date).toLocaleDateString(lang)}</td
									>
									<td class="border-2 border-gray-600 p-2">{history.comments}</td>
								</tr>
							{/each}
						</tbody>
					</table>
				</div>
			{/if}
		</div>
	{/if}
	{#if largeScreen}
		{#if showControls}
			<div class=" absolute bottom-0 right-0 z-20 h-full pointer-events-none">
				<div class="pr-4 pt-14 pb-8 w-[24rem] h-full" in:slide={{ duration: 200, axis: 'x' }}>
					<div
						class="w-full h-full px-5 py-4 bg-white dark:shadow-lg dark:bg-gray-850 border border-gray-50 dark:border-gray-800 rounded-xl z-50 pointer-events-auto overflow-y-auto scrollbar-hidden"
					>
						<Controls
							on:close={() => {
								showControls = false;
								hideSupportWidgetBtn.set(false);
							}}
							models={chatControlModels}
						/>
					</div>
				</div>
			</div>
		{/if}
	{:else}
		<Modal bind:show={showControls}>
			<div class="px-6 py-4 h-full">
				<Controls
					on:close={() => {
						showControls = false;
						hideSupportWidgetBtn.set(false);
					}}
					models={chatControlModels}
				/>
			</div>
		</Modal>
	{/if}
</div>

<style>
	.hidden {
		visibility: hidden;
		margin: 0;
		padding: 0;
		height: 0;
	}

	:global(#eot-doc-wrapper ul > li::before) {
		content: '●';
		color: #9b9b9b;
		font-weight: 100;
		font-size: 1em;
		display: inline-block;
		height: 0.25em;
		text-align: left;
		padding-right: 0.5rem;
	}

	:global(#eot-doc-wrapper ul > li) {
		margin: 6px;
	}

	:global(#eot-doc-wrapper ul > li > a) {
		color: #0051af;
		font-size: 1rem;
		font-family: 'CiscoSansThin';
		font-weight: 700;
	}

	#eot-doc-wrapper .cdt-best-practice:before {
		color: #6cc04a;
		content: '\272A  Best Practice:';
		font-size: 14px;
		font-weight: 700;
		line-height: 2em;
		-webkit-transition: all 0.3s ease;
		-o-transition: all 0.3s ease;
		transition: all 0.3s ease;
	}
</style>
